-- 파일 최상단에 추가
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE DATABASE IF NOT EXISTS ocean_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ocean_db;

CREATE TABLE `USERS` (
    `USER_ID` VARCHAR(50) PRIMARY KEY COMMENT '사용자 ID (소셜 로그인 ID)',
    `PROVIDER` VARCHAR(20) NOT NULL COMMENT 'OAuth 제공자 (google, kakao)',
    `USER_NM` VARCHAR(50) NOT NULL COMMENT '사용자 이름',
    `USER_IMG` VARCHAR(255) COMMENT '프로필 이미지 URL',
    `LANGUAGE_SETTING` VARCHAR(10) DEFAULT 'ko' COMMENT '언어 설정',
    `ACTIVE_STATE` CHAR(1) DEFAULT 'Y' COMMENT '활성 상태 (Y/N)',
    `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    INDEX `idx_provider` (`PROVIDER`),
    INDEX `idx_created` (`CREATED_DATE`)
) COMMENT = '사용자 기본 정보';

CREATE TABLE `USER_TOKENS` (
    `TOKEN_ID` VARCHAR(100) PRIMARY KEY COMMENT '토큰 ID',
    `USER_ID` VARCHAR(50) NOT NULL COMMENT '사용자 ID',
    `ACCESS_TOKEN` VARCHAR(500) COMMENT 'OAuth 액세스 토큰',
    `REFRESH_TOKEN` VARCHAR(500) COMMENT 'OAuth 리프레시 토큰',
    `TOKEN_EXPIRES_TIME` TIMESTAMP NULL COMMENT '토큰 만료 시간',
    `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `MODIFY` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`USER_ID`) ON DELETE CASCADE,
    INDEX `idx_user_id` (`USER_ID`),
    INDEX `idx_expires` (`TOKEN_EXPIRES_TIME`)
) COMMENT = '사용자 인증 토큰 관리';

CREATE TABLE `WORKSPACE` (
    `WORKSPACE_CD` VARCHAR(100) PRIMARY KEY COMMENT '워크스페이스 코드',
    `WORKSPACE_NM` VARCHAR(100) NOT NULL COMMENT '워크스페이스 이름',
    `WORKSPACE_IMG` VARCHAR(255) COMMENT '워크스페이스 이미지',
    `INVITE_CD` VARCHAR(12) UNIQUE COMMENT '초대 코드',
    `ACTIVE_STATE` CHAR(1) DEFAULT 'Y' COMMENT '활성 상태',
    `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `END_DATE` TIMESTAMP NULL COMMENT '종료일',
    INDEX `idx_invite_cd` (`INVITE_CD`),
    INDEX `idx_active` (`ACTIVE_STATE`)
) COMMENT = '워크스페이스 정보';

CREATE TABLE `WORKSPACE_DEPT` (
    `DEPT_CD` VARCHAR(10) PRIMARY KEY COMMENT '부서 코드',
    `DEPT_NM` VARCHAR(30) NOT NULL COMMENT '부서명',
    `WORKSPACE_CD` VARCHAR(100) NOT NULL COMMENT '워크스페이스 코드',
    FOREIGN KEY (`WORKSPACE_CD`) REFERENCES `WORKSPACE`(`WORKSPACE_CD`) ON DELETE CASCADE
) COMMENT = '워크스페이스 부서 정보';

CREATE TABLE `WORKSPACE_MEMBERS` (
    `WORKSPACE_CD` VARCHAR(100) NOT NULL COMMENT '워크스페이스 코드',
    `USER_ID` VARCHAR(50) NOT NULL COMMENT '사용자 ID',
    `USER_NICKNAME` VARCHAR(50) COMMENT '사용자 닉네임',
    `USER_ROLE` VARCHAR(10) DEFAULT 'MEMBER' COMMENT '역할 (ADMIN/MEMBER)',
    `STATUS_MSG` VARCHAR(100) COMMENT '상태 메시지',
    `USER_IMG` VARCHAR(255) COMMENT '프로필 이미지 경로',
    `DEPT_CD` VARCHAR(10) COMMENT '부서 코드',
    `POSITION` VARCHAR(30) COMMENT '직급',
    `EMAIL` VARCHAR(255) COMMENT '이메일',
    `PHONE_NUM` VARCHAR(20) COMMENT '전화번호',
    `ACTIVE_STATE` CHAR(1) DEFAULT 'Y' COMMENT '활성 상태',
    `FAVORITE` CHAR(1) DEFAULT 'N' COMMENT '즐겨찾기 여부',
    `JOINED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '가입일',
    `ENTRANCE_DATE` TIMESTAMP NULL COMMENT '입장일',
    `QUIT_DATE` TIMESTAMP NULL COMMENT '퇴장일',
    PRIMARY KEY (`WORKSPACE_CD`, `USER_ID`),
    FOREIGN KEY (`WORKSPACE_CD`) REFERENCES `WORKSPACE`(`WORKSPACE_CD`) ON DELETE CASCADE,
    FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`USER_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`DEPT_CD`) REFERENCES `WORKSPACE_DEPT`(`DEPT_CD`) ON DELETE SET NULL,
    INDEX `idx_user` (`USER_ID`),
    INDEX `idx_role` (`USER_ROLE`),
    INDEX `idx_active` (`ACTIVE_STATE`)
) COMMENT = '워크스페이스 멤버 정보';

CREATE TABLE `INVITATIONS` (
    `WORKSPACE_CD` VARCHAR(100) NOT NULL COMMENT '워크스페이스 코드',
    `INVITED_USER_ID` VARCHAR(50) NOT NULL COMMENT '초대받은 사용자 ID',
    `INVITE_CD` VARCHAR(12) NOT NULL COMMENT '초대 코드',
    `STATUS` VARCHAR(10) DEFAULT 'PENDING' COMMENT '상태 (PENDING/ACCEPTED/REJECTED)',
    `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`WORKSPACE_CD`, `INVITED_USER_ID`),
    FOREIGN KEY (`WORKSPACE_CD`) REFERENCES `WORKSPACE`(`WORKSPACE_CD`) ON DELETE CASCADE,
    FOREIGN KEY (`INVITED_USER_ID`) REFERENCES `USERS`(`USER_ID`) ON DELETE CASCADE,
    INDEX `idx_invite_cd` (`INVITE_CD`),
    INDEX `idx_status` (`STATUS`)
) COMMENT = '워크스페이스 초대 관리';

CREATE TABLE `EVENTS` (
    `EVENT_CD` VARCHAR(100) PRIMARY KEY COMMENT '이벤트 코드',
    `WORKSPACE_CD` VARCHAR(100) COMMENT '워크스페이스 코드',
    `USER_ID` VARCHAR(50) NOT NULL COMMENT '생성자 ID',
    `TITLE` VARCHAR(90) NOT NULL COMMENT '제목',
    `DESCRIPTION` TEXT COMMENT '설명',
    `START_DATETIME` DATETIME NOT NULL COMMENT '시작 일시',
    `END_DATETIME` DATETIME NOT NULL COMMENT '종료 일시',
    `COLOR` VARCHAR(10) DEFAULT '#0066CC' COMMENT '색상',
    `IS_SHARED` CHAR(1) DEFAULT 'N' COMMENT '공유 여부',
    `PROGRESS_STATUS` VARCHAR(10) DEFAULT 'TODO' COMMENT '진행 상태 (TODO/IN_PROGRESS/DONE)',
    `PRIORITY` VARCHAR(10) DEFAULT 'NORMAL' COMMENT '우선순위 (LOW/NORMAL/HIGH)',
    `CREATED_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `NOTIFY_TIME` INT NOT NULL COMMENT '알림 시간 (분 단위)',
    FOREIGN KEY (`WORKSPACE_CD`) REFERENCES `WORKSPACE`(`WORKSPACE_CD`) ON DELETE CASCADE,
    FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`USER_ID`) ON DELETE CASCADE,
    INDEX `idx_workspace` (`WORKSPACE_CD`),
    INDEX `idx_user` (`USER_ID`),
    INDEX `idx_datetime` (`START_DATETIME`, `END_DATETIME`),
    INDEX `idx_status` (`PROGRESS_STATUS`)
) COMMENT = '일정/이벤트 정보';

CREATE TABLE `EVENT_ATTENDENCES` (
    `EVENT_CD` VARCHAR(100),
    `USER_ID` VARCHAR(50),
    PRIMARY KEY (`EVENT_CD`, `USER_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`USER_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`EVENT_CD`) REFERENCES `EVENTS`(`EVENT_CD`) ON DELETE CASCADE
);

CREATE TABLE `MAIN_NOTIFICATION` (
    `WORKSPACE_CD` VARCHAR(100) PRIMARY KEY,
    `NOTI_STATE` VARCHAR(20) NOT NULL COMMENT 'ENUM (NEW_EVENT, MODI_EVENT, DEL_EVENT, NEW_ATTENDENCE, NEW_MEETING, NEW_FILE)',
    `CREATED_BY` VARCHAR(50),
    `CREATED_DATE` DATETIME,
    FOREIGN KEY (`WORKSPACE_CD`) REFERENCES `WORKSPACE`(`WORKSPACE_CD`) ON DELETE CASCADE
);

CREATE TABLE `MENTION_NOTIFICATION` (
    `EVENT_CD` VARCHAR(100) PRIMARY KEY,
    `USER_ID` VARCHAR(50),
    `NOTI_STATE` VARCHAR(20) NOT NULL COMMENT 'ENUM (NEW, MODIFY, DELETE)',
    `READ_STATE` CHAR(1) DEFAULT 'N',
    FOREIGN KEY (`EVENT_CD`) REFERENCES `EVENT_ATTENDENCES`(`EVENT_CD`) ON DELETE CASCADE,
    FOREIGN KEY (`USER_ID`) REFERENCES `EVENT_ATTENDENCES`(`USER_ID`) ON DELETE CASCADE
);

CREATE TABLE `PLACE` (
    `PLACE_CD` INT AUTO_INCREMENT PRIMARY KEY COMMENT '장소 코드',
    `EVENT_CD` VARCHAR(100) COMMENT '이벤트 코드',
    `PLACE_NM` VARCHAR(255) NOT NULL COMMENT '장소명',
    `ADDRESS` VARCHAR(255) NOT NULL COMMENT '주소',
    `LAT` DOUBLE NOT NULL COMMENT '위도',
    `LNG` DOUBLE NOT NULL COMMENT '경도',
    `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `MODIFY` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`EVENT_CD`) REFERENCES `EVENTS`(`EVENT_CD`) ON DELETE CASCADE,
    INDEX `idx_event` (`EVENT_CD`),
    INDEX `idx_location` (`LAT`, `LNG`)
) COMMENT = '장소 정보';

CREATE TABLE `MEETING_ROOMS` (
    `ROOM_CD` VARCHAR(100) PRIMARY KEY COMMENT '회의실 코드',
    `ROOM_NM` VARCHAR(100) NOT NULL COMMENT '회의실 이름',
    `DESCRIPTION` TEXT COMMENT '회의 설명',
    `WORKSPACE_CD` VARCHAR(100) NOT NULL COMMENT '워크스페이스 코드',
    `HOST_ID` VARCHAR(50) NOT NULL COMMENT '호스트 ID',
    `STATUS` VARCHAR(20) DEFAULT 'WAITING' COMMENT '상태 (WAITING/IN_PROGRESS/ENDED)',
    `RECORDING_ENABLE` CHAR(1) DEFAULT 'N' COMMENT '녹화 가능 여부',
    `RECORDING_PATH` VARCHAR(500) COMMENT '녹화 파일 경로',
    `ACTUAL_START_TIME` TIMESTAMP NULL COMMENT '실제 시작 시간',
    `ACTUAL_END_TIME` TIMESTAMP NULL COMMENT '실제 종료 시간',
    FOREIGN KEY (`WORKSPACE_CD`) REFERENCES `WORKSPACE`(`WORKSPACE_CD`) ON DELETE CASCADE,
    FOREIGN KEY (`HOST_ID`) REFERENCES `USERS`(`USER_ID`) ON DELETE CASCADE,
    INDEX `idx_workspace` (`WORKSPACE_CD`),
    INDEX `idx_host` (`HOST_ID`),
    INDEX `idx_status` (`STATUS`)
) COMMENT = '화상회의실 정보';

CREATE TABLE `MEETING_PARTICIPANTS` (
    `ROOM_CD` VARCHAR(100) NOT NULL COMMENT '회의실 코드',
    `USER_ID` VARCHAR(50) NOT NULL COMMENT '참가자 ID',
    `JOINED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '입장 시간',
    `QUIT_DATE` TIMESTAMP NULL COMMENT '퇴장 시간',
    `ACTIVE_STATE` CHAR(1) DEFAULT 'Y' COMMENT '활성 상태',
    `ROLE` VARCHAR(20) DEFAULT 'PARTICIPANT' COMMENT '역할 (HOST/PARTICIPANT)',
    `VIDEO_STATE` CHAR(1) DEFAULT 'Y' COMMENT '비디오 상태',
    `AUDIO_STATE` CHAR(1) DEFAULT 'Y' COMMENT '오디오 상태',
    `SHARING_STATE` CHAR(1) DEFAULT 'N' COMMENT '화면 공유 상태',
    `CONN_QUALITY` VARCHAR(10) COMMENT '연결 품질',
    PRIMARY KEY (`ROOM_CD`, `USER_ID`),
    FOREIGN KEY (`ROOM_CD`) REFERENCES `MEETING_ROOMS`(`ROOM_CD`) ON DELETE CASCADE,
    FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`USER_ID`) ON DELETE CASCADE,
    INDEX `idx_active` (`ACTIVE_STATE`)
) COMMENT = '회의 참가자 정보';

CREATE TABLE `MEETING_DOCUMENTS` (
    `DOCUMENT_CD` VARCHAR(100) PRIMARY KEY COMMENT '문서 코드',
    `ROOM_CD` VARCHAR(100) NOT NULL COMMENT '회의실 코드',
    `FILE_NM` VARCHAR(300) NOT NULL COMMENT '파일명',
    `FILE_TYPE` VARCHAR(10) NOT NULL COMMENT '파일 타입',
    `FILE_PATH` VARCHAR(500) NOT NULL COMMENT '파일 경로',
    `FILE_SIZE` BIGINT NOT NULL COMMENT '파일 크기',
    `TOTAL_PAGES` INT COMMENT '총 페이지 수',
    `CONVERSION_STATUS` VARCHAR(15) DEFAULT 'PENDING' COMMENT '변환 상태',
    `UPLOADED_BY` VARCHAR(50) NOT NULL COMMENT '업로드한 사용자',
    `UPLOADED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `CONVERTED_DATE` TIMESTAMP NULL COMMENT '변환 완료 시간',
    `ACTIVE_STATE` CHAR(1) DEFAULT 'Y' COMMENT '활성 상태',
    FOREIGN KEY (`ROOM_CD`) REFERENCES `MEETING_ROOMS`(`ROOM_CD`) ON DELETE CASCADE,
    FOREIGN KEY (`UPLOADED_BY`) REFERENCES `USERS`(`USER_ID`) ON DELETE CASCADE,
    INDEX `idx_room` (`ROOM_CD`),
    INDEX `idx_status` (`CONVERSION_STATUS`)
) COMMENT = '회의 문서 정보';

-- MEETING_OPTIONS 테이블 생성
CREATE TABLE `MEETING_OPTIONS` (
    `OPTION_ID` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '옵션 ID',
    `ROOM_CD` VARCHAR(100) NOT NULL COMMENT '회의실 코드',
    `AUTO_RECORD` CHAR(1) DEFAULT 'N' COMMENT '자동 녹화 여부',
    `MUTE_ON_JOIN` CHAR(1) DEFAULT 'N' COMMENT '입장 시 음소거',
    `WAITING_ROOM` CHAR(1) DEFAULT 'N' COMMENT '대기실 사용 여부',
    `VIDEO_QUALITY` VARCHAR(10) DEFAULT 'HD' COMMENT '비디오 품질 (HD/FHD/SD)',
    `CHAT_ENABLED` CHAR(1) DEFAULT 'Y' COMMENT '채팅 활성화',
    `SCREEN_SHARE_ENABLED` CHAR(1) DEFAULT 'Y' COMMENT '화면 공유 허용',
    `FILE_SHARE_ENABLED` CHAR(1) DEFAULT 'Y' COMMENT '파일 공유 허용',
    `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`ROOM_CD`) REFERENCES `MEETING_ROOMS`(`ROOM_CD`) ON DELETE CASCADE,
    INDEX `idx_room` (`ROOM_CD`)
) COMMENT = '회의 옵션 정보';


-- 녹화 파일 관리 테이블
CREATE TABLE `RECORDING_FILES` (
    `RECORDING_ID` VARCHAR(100) PRIMARY KEY COMMENT '녹화 ID',
    `ROOM_CD` VARCHAR(100) NOT NULL COMMENT '회의실 코드',
    `WORKSPACE_CD` VARCHAR(100) NOT NULL COMMENT '워크스페이스 코드',
    `RECORDER_ID` VARCHAR(50) NOT NULL COMMENT '녹화 시작한 사용자 ID',
    `FILE_NM` VARCHAR(255) NOT NULL COMMENT '파일명',
    `FILE_PATH` VARCHAR(500) NOT NULL COMMENT '파일 경로',
    `FILE_SIZE` BIGINT COMMENT '파일 크기 (bytes)',
    `DURATION` INT COMMENT '녹화 시간 (초)',
    `RECORDING_STATUS` VARCHAR(20) DEFAULT 'RECORDING' COMMENT '녹화 상태 (RECORDING/COMPLETED/FAILED)',
    `START_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '녹화 시작 시간',
    `END_TIME` TIMESTAMP NULL COMMENT '녹화 종료 시간',
    `THUMBNAIL_PATH` VARCHAR(500) COMMENT '썸네일 경로',
    `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `MODIFY` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`ROOM_CD`) REFERENCES `MEETING_ROOMS`(`ROOM_CD`) ON DELETE CASCADE,
    FOREIGN KEY (`WORKSPACE_CD`) REFERENCES `WORKSPACE`(`WORKSPACE_CD`) ON DELETE CASCADE,
    FOREIGN KEY (`RECORDER_ID`) REFERENCES `USERS`(`USER_ID`),
    INDEX `idx_room` (`ROOM_CD`),
    INDEX `idx_workspace` (`WORKSPACE_CD`),
    INDEX `idx_status` (`RECORDING_STATUS`),
    INDEX `idx_created` (`CREATED_DATE`)
) COMMENT = '녹화 파일 정보';

-- 녹화 파일 접근 권한 테이블
CREATE TABLE `RECORDING_ACCESS` (
    `ACCESS_ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `RECORDING_ID` VARCHAR(100) NOT NULL COMMENT '녹화 ID',
    `USER_ID` VARCHAR(50) NOT NULL COMMENT '접근 가능한 사용자 ID',
    `ACCESS_TYPE` VARCHAR(20) DEFAULT 'VIEW' COMMENT '접근 권한 (VIEW/DOWNLOAD/DELETE)',
    `GRANTED_BY` VARCHAR(50) NOT NULL COMMENT '권한 부여한 사용자',
    `GRANTED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`RECORDING_ID`) REFERENCES `RECORDING_FILES`(`RECORDING_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`USER_ID`),
    UNIQUE KEY `uk_recording_user` (`RECORDING_ID`, `USER_ID`)
) COMMENT = '녹화 파일 접근 권한';

-- 녹화 시청 로그 테이블
CREATE TABLE `RECORDING_VIEW_LOG` (
    `LOG_ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `RECORDING_ID` VARCHAR(100) NOT NULL COMMENT '녹화 ID',
    `VIEWER_ID` VARCHAR(50) NOT NULL COMMENT '시청자 ID',
    `VIEW_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '시청 시간',
    `VIEW_DURATION` INT DEFAULT 0 COMMENT '시청 시간 (초)',
    `IP_ADDRESS` VARCHAR(50) COMMENT 'IP 주소',
    FOREIGN KEY (`RECORDING_ID`) REFERENCES `RECORDING_FILES`(`RECORDING_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`VIEWER_ID`) REFERENCES `USERS`(`USER_ID`),
    INDEX `idx_recording` (`RECORDING_ID`),
    INDEX `idx_viewer` (`VIEWER_ID`),
    INDEX `idx_view_date` (`VIEW_DATE`)
) COMMENT = '녹화 시청 로그';

CREATE TABLE `DOCUMENT_ANNOTATIONS` (
    `ANNOTATION_ID` VARCHAR(100) PRIMARY KEY COMMENT '주석 ID',
    `DOCUMENT_CD` VARCHAR(100) NOT NULL COMMENT '문서 코드',
    `PAGE_NUMBER` INT NOT NULL COMMENT '페이지 번호',
    `ANNOTATION_DATA` JSON NOT NULL COMMENT '주석 데이터',
    `ANNOTATION_TYPE` VARCHAR(20) NOT NULL COMMENT '주석 타입',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `IS_VISIBLE` CHAR(1) DEFAULT 'Y' COMMENT '표시 여부',
    FOREIGN KEY (`DOCUMENT_CD`) REFERENCES `MEETING_DOCUMENTS`(`DOCUMENT_CD`) ON DELETE CASCADE,
    FOREIGN KEY (`CREATED_BY`) REFERENCES `USERS`(`USER_ID`) ON DELETE CASCADE,
    INDEX `idx_document_page` (`DOCUMENT_CD`, `PAGE_NUMBER`),
    INDEX `idx_creator` (`CREATED_BY`)
) COMMENT = '문서 주석 정보';

CREATE TABLE `CHAT_MSG` (
    `MSG_ID` VARCHAR(100) PRIMARY KEY COMMENT '메시지 ID',
    `ROOM_CD` VARCHAR(100) NOT NULL COMMENT '회의실 코드',
    `SENDER_ID` VARCHAR(50) NOT NULL COMMENT '발신자 ID',
    `MSG_TYPE` VARCHAR(10) DEFAULT 'TEXT' COMMENT '메시지 타입 (TEXT/FILE)',
    `MSG_CONTENT` TEXT COMMENT '메시지 내용',
    `FILE_PATH` VARCHAR(500) COMMENT '파일 경로',
    `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`ROOM_CD`) REFERENCES `MEETING_ROOMS`(`ROOM_CD`) ON DELETE CASCADE,
    FOREIGN KEY (`SENDER_ID`) REFERENCES `USERS`(`USER_ID`) ON DELETE CASCADE,
    INDEX `idx_room_date` (`ROOM_CD`, `CREATED_DATE`),
    INDEX `idx_sender` (`SENDER_ID`)
) COMMENT = '채팅 메시지 정보';

CREATE TABLE `FILE` (
    `FILE_ID` VARCHAR(100) PRIMARY KEY,
    `EVENT_CD` VARCHAR(100) NOT NULL,
    `FILE_NM` VARCHAR(300) NOT NULL,
    `FILE_TYPE` VARCHAR(10) NOT NULL,
    `FILE_PATH` VARCHAR(500) NOT NULL,
    `FILE_SIZE` BIGINT NOT NULL,
    `UPLOADED_BY` VARCHAR(50) NOT NULL,
    `UPLOADED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `ACTIVE_STATE` CHAR(1) DEFAULT 'Y',
    FOREIGN KEY (`EVENT_CD`) REFERENCES `EVENTS`(`EVENT_CD`) ON DELETE CASCADE
) COMMENT = '파일';

/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;